import type { CardPreset } from '../../../components/card-workshop/shared/types';

const durableVisualImportance = {
  namedStatus: true,
  narrativeWeight: 'major' as const,
  recurrence: true,
  plotRelevance: true,
};

export const CARD_PRESETS: CardPreset[] = [
  {
    id: 'preset-human-character',
    title: 'Human Portrait',
    subtitle: 'Rin the First Witness',
    kind: 'codex-card',
    description: 'A human Portrait resolved from first-reveal metadata through the visual Codex path.',
    explanation: {
      componentName: 'CodexCard',
      sourceFile: 'src/components/reader-chamber/development/CodexCard.tsx',
      currentTrigger: 'metadata.entities character reveal resolves to an application-owned Human Portrait',
      entityOrEventType: 'character (human individual)',
      codexDestination: 'ReaderCodex > Portraits (Human Section)',
      capabilities: { hasImage: true, hasManifestAction: true, hasAudio: true, hasCodexLink: true, hasQuoteOrProse: true },
      architecturalNotes: 'The Reader uses stored Codex media and never accepts a model-generated Codex ID or image URL. Audio direction remains in the existing chapter payload; this Codex Card preview does not decide its future audio interaction.',
    },
    codexReveal: {
      type: 'Human Portrait',
      entry: {
        id: 'codex-char-rin',
        name: 'Rin',
        description: 'A disgraced oath-reader who can see where sacred vows fray in the atmospheric rain.',
        portraitKind: 'human',
        imageUrl: '/card-workshop/test-images/ye_chen_portrait.png',
        manifestationImportance: durableVisualImportance,
      },
    },
  },
  {
    id: 'preset-nonhuman-individual',
    title: 'Non-Human Portrait',
    subtitle: 'Lei the Thunder Drake Companion',
    kind: 'codex-card',
    description: 'A persistent named non-human individual resolved as a Portrait, not a species image.',
    explanation: {
      componentName: 'CodexCard',
      sourceFile: 'src/components/reader-chamber/development/CodexCard.tsx',
      currentTrigger: 'metadata.entities character reveal resolves to a Portrait with portraitKind: "non-human"',
      entityOrEventType: 'character (important non-human individual)',
      codexDestination: 'ReaderCodex > Portraits (Non-Human Section) + Bestiary link',
      capabilities: { hasImage: true, hasManifestAction: true, hasAudio: true, hasCodexLink: true, hasQuoteOrProse: true },
      architecturalNotes: 'Named, bonded, intelligent, or recurring individuals are character-owned Portraits. Their species remains informational. Audio direction remains in the existing chapter payload; this preview does not decide its future Codex Card interaction.',
    },
    codexReveal: {
      type: 'Non-Human Portrait',
      entry: {
        id: 'codex-char-lei',
        name: 'Lei',
        description: 'A young thunder dragon whose scales hold living arcs of celestial lightning.',
        portraitKind: 'non-human',
        speciesName: 'Thunder Dragons',
        imageUrl: '/card-workshop/test-images/lyra_meadowlight_portrait.png',
        manifestationImportance: durableVisualImportance,
      },
    },
  },
  {
    id: 'preset-artifact-relic',
    title: 'Artifact',
    subtitle: 'Nine Cauldrons Oath Seal',
    kind: 'codex-card',
    description: 'A visually presented Artifact resolved through the Codex reveal path.',
    explanation: {
      componentName: 'CodexCard',
      sourceFile: 'src/components/reader-chamber/development/CodexCard.tsx',
      currentTrigger: 'metadata.entities artifact reveal resolves to the stored Artifact entry',
      entityOrEventType: 'artifact',
      codexDestination: 'ReaderCodex > Artifacts',
      capabilities: { hasImage: true, hasManifestAction: true, hasAudio: true, hasCodexLink: true, hasQuoteOrProse: true },
      architecturalNotes: 'Existing artwork displays from the Codex; an eligible missing image retains the existing Manifest action. Activation audio direction remains in the existing chapter payload; this preview does not decide its future Codex Card interaction.',
    },
    codexReveal: {
      type: 'Artifact',
      entry: {
        id: 'codex-art-oath-seal',
        name: 'Nine Cauldrons Oath Seal',
        description: 'Forged during the Second Era to enforce non-aggression treaties between mortal dynasties.',
        imageUrl: '/card-workshop/test-images/elder_kaelen_portrait.png',
        manifestationImportance: durableVisualImportance,
      },
    },
  },
  {
    id: 'preset-location',
    title: 'Location',
    subtitle: 'Rain Court Grand Pavilion',
    kind: 'codex-card',
    description: 'A visually presented Location resolved through the Codex reveal path.',
    explanation: {
      componentName: 'CodexCard',
      sourceFile: 'src/components/reader-chamber/development/CodexCard.tsx',
      currentTrigger: 'metadata.entities location reveal resolves to the stored Location entry',
      entityOrEventType: 'location',
      codexDestination: 'ReaderCodex > Locations',
      capabilities: { hasImage: true, hasManifestAction: true, hasAudio: true, hasCodexLink: true, hasQuoteOrProse: true },
      architecturalNotes: 'The card displays application-owned Codex artwork or the existing Manifest state. Signature audio direction remains in the existing chapter payload; this preview does not decide its future Codex Card interaction.',
    },
    codexReveal: {
      type: 'Location',
      entry: {
        id: 'codex-loc-rain-court',
        name: 'Rain Court Grand Pavilion',
        description: 'The ancient administrative center where false vows trigger celestial thunder.',
        imageUrl: '/card-workshop/test-images/lotus_lake_pavilion_portrait.jpg',
        manifestationImportance: durableVisualImportance,
      },
    },
  },
  {
    id: 'preset-creature-species',
    title: 'Highlighted Bestiary Species',
    subtitle: 'Shadow Void Stalker',
    kind: 'world-card',
    description: 'A species remains an informational Bestiary record and uses a World Card only for a chapter highlight.',
    explanation: {
      componentName: 'WorldCard',
      sourceFile: 'src/components/reader-chamber/development/WorldCard.tsx',
      currentTrigger: 'worldCard with entityType: "creature" for a highlighted species moment',
      entityOrEventType: 'creature (species)',
      codexDestination: 'ReaderCodex > Bestiary (informational record)',
      capabilities: { hasImage: false, hasManifestAction: false, hasAudio: true, hasCodexLink: true, hasQuoteOrProse: true },
      architecturalNotes: 'The species does not receive generated Codex artwork, a Manifest action, or a Codex Card.',
    },
    worldCard: {
      entityType: 'creature',
      entityName: 'Shadow Void Stalker',
      displayTitle: 'Apex Abyss Beast',
      quote: 'It walks between breaths, leaving frost where blood once flowed.',
      audioType: 'hiss',
      sound: { assetId: 'card-workshop-sample', tags: ['void', 'stalker'] },
    },
  },
  {
    id: 'preset-faction',
    title: 'Highlighted Faction',
    subtitle: 'The Ninth House of Oaths',
    kind: 'world-card',
    description: 'A Faction remains an informational Codex record and uses a World Card only when highlighted.',
    explanation: {
      componentName: 'WorldCard',
      sourceFile: 'src/components/reader-chamber/development/WorldCard.tsx',
      currentTrigger: 'worldCard with entityType: "faction" for a highlighted faction moment',
      entityOrEventType: 'faction',
      codexDestination: 'ReaderCodex > Factions (informational record)',
      capabilities: { hasImage: false, hasManifestAction: false, hasAudio: true, hasCodexLink: true, hasQuoteOrProse: true },
      architecturalNotes: 'Factions do not receive generated Codex artwork, Manifest actions, or Codex Cards.',
    },
    worldCard: {
      entityType: 'faction',
      entityName: 'The Ninth House of Oaths',
      displayTitle: 'Judicial Enforcement Syndicate',
      quote: 'A word spoken is an anchor cast into the river of fate.',
      audioType: 'chant',
      sound: { assetId: 'card-workshop-sample', tags: ['oath', 'procession'] },
    },
  },
  {
    id: 'preset-random-beast',
    title: 'Random Encounter Beast',
    subtitle: 'Ash-Maw Prowler',
    kind: 'world-card',
    description: 'A disposable encounter-only beast may receive a World Card when the moment earns a highlight.',
    explanation: {
      componentName: 'WorldCard',
      sourceFile: 'src/components/reader-chamber/development/WorldCard.tsx',
      currentTrigger: 'worldCard with entityType: "creature" without a persistent individual Portrait',
      entityOrEventType: 'creature (encounter-only individual)',
      codexDestination: 'Bestiary species update only when applicable',
      capabilities: { hasImage: false, hasManifestAction: false, hasAudio: true, hasCodexLink: false, hasQuoteOrProse: true },
      architecturalNotes: 'The encounter does not manufacture a persistent Portrait or model-owned visual identity.',
    },
    worldCard: {
      entityType: 'creature',
      entityName: 'Ash-Maw Prowler',
      displayTitle: 'The Beast Beneath the Cinders',
      quote: 'Its jaws opened like a furnace door.',
      audioType: 'roar',
      sound: { assetId: 'card-workshop-sample', element: 'fire', tags: ['encounter', 'cinders'] },
    },
  },
  {
    id: 'preset-system-status',
    title: 'System Status',
    subtitle: 'Cultivation Meridian Alignment',
    kind: 'system-block',
    description: 'A structured RPG status window showing stats, stage, and progression meters.',
    explanation: {
      componentName: 'SystemBlock',
      sourceFile: 'src/components/reader-chamber/development/SystemBlock.tsx',
      currentTrigger: 'Structured block.system status update',
      entityOrEventType: 'system (status)',
      codexDestination: 'ReaderCodex > Power Rankings',
      capabilities: { hasImage: false, hasManifestAction: false, hasAudio: false, hasCodexLink: true, hasQuoteOrProse: true },
      architecturalNotes: 'System content remains a separate chapter-generation mechanic and presentation.',
    },
    systemContent: '[ SYSTEM NOTIFICATION: Meridian Resonance 84% — Minor Bottleneck Cleared ]',
    systemEvent: {
      kind: 'status',
      title: 'Meridian Status & Vitality Flow',
      rarity: 'First Witness Core Resonance',
      rows: [
        { label: 'Cultivation Stage', value: 'Foundation Establishment — Stage 4' },
        { label: 'Spiritual Qi Pool', value: '1,420 / 1,500 (+12/min in Rain)' },
        { label: 'Soul Seam Sight', value: 'Active (Radius: 30 paces)' },
        { label: 'Dao Alignment', value: 'Unbroken Celestial Truth' },
      ],
    },
  },
  {
    id: 'preset-skill-acquired',
    title: 'Skill Acquisition',
    subtitle: 'Cloud Steps & Seam Stride',
    kind: 'system-block',
    description: 'Instant notification when the protagonist unlocks or masters a martial technique.',
    explanation: {
      componentName: 'SystemBlock',
      sourceFile: 'src/components/reader-chamber/development/SystemBlock.tsx',
      currentTrigger: 'Structured block.system skill acquisition event',
      entityOrEventType: 'system (skill_acquired)',
      codexDestination: 'ReaderCodex > Power Rankings (Ability Ledger)',
      capabilities: { hasImage: false, hasManifestAction: false, hasAudio: false, hasCodexLink: true, hasQuoteOrProse: true },
    },
    systemContent: '[ SKILL ACQUIRED: Seam Stride (Earth Grade — Initial Mastery) ]',
    systemEvent: {
      kind: 'skill_acquired',
      title: 'New Technique Comprehended',
      rarity: 'Earth Grade · Movement Dao',
      rows: [
        { label: 'Skill Name', value: 'Seam Stride' },
        { label: 'Grade', value: 'Earth Grade (Tier 2)' },
        { label: 'Cost', value: '35 Qi per stride' },
        { label: 'Effect', value: 'Phases along the shortest path between two observed vow lines.' },
      ],
    },
  },
  {
    id: 'preset-level-up',
    title: 'Level-Up / Breakthrough',
    subtitle: 'Core Formation Breakthrough',
    kind: 'system-block',
    description: 'Major narrative breakthrough with golden ascension borders and massive stat leaps.',
    explanation: {
      componentName: 'SystemBlock',
      sourceFile: 'src/components/reader-chamber/development/SystemBlock.tsx',
      currentTrigger: 'Structured block.system level-up event',
      entityOrEventType: 'system (level_up)',
      codexDestination: 'ReaderCodex > Power Rankings',
      capabilities: { hasImage: false, hasManifestAction: false, hasAudio: false, hasCodexLink: true, hasQuoteOrProse: true },
    },
    systemContent: '[ BREAKTHROUGH: Core Formation Stage 1 Reached — Longevity +150 Years ]',
    systemEvent: {
      kind: 'level_up',
      title: 'Ascension Milestone Achieved',
      rarity: 'Mortal Tribulation Surpassed',
      rows: [
        { label: 'Previous Realm', value: 'Foundation Establishment Peak' },
        { label: 'New Realm', value: 'Core Formation — Stage 1' },
        { label: 'Lifespan Extension', value: '+150 Solar Cycles' },
        { label: 'Divine Sense', value: 'Expanded to 500 Meters' },
      ],
    },
  },
  {
    id: 'preset-quest-appraisal',
    title: 'Quest & Appraisal',
    subtitle: 'Trial of the Sovereign Seal',
    kind: 'system-block',
    description: 'System-mandated mission objectives with rewards and deadline conditions.',
    explanation: {
      componentName: 'SystemBlock',
      sourceFile: 'src/components/reader-chamber/development/SystemBlock.tsx',
      currentTrigger: 'Structured block.system quest or appraisal event',
      entityOrEventType: 'system (quest / appraisal)',
      codexDestination: 'ReaderCodex > Karma Ledger & Threads',
      capabilities: { hasImage: false, hasManifestAction: false, hasAudio: false, hasCodexLink: true, hasQuoteOrProse: true },
    },
    systemContent: '[ QUEST ISSUED: Uncover the Magistrate\'s Forged Decree Before Dusk ]',
    systemEvent: {
      kind: 'quest',
      title: 'Mandatory Karmic Task',
      rarity: 'Time Limit: 4 Hours',
      rows: [
        { label: 'Primary Objective', value: 'Inspect the 7th Archive without tripping blood wards' },
        { label: 'Success Reward', value: 'Heavenly Oath Fragment x 1' },
        { label: 'Failure Penalty', value: 'Meridian Backlash (Loss of Stage 1 Qi)' },
      ],
    },
  },
  {
    id: 'preset-fate-result',
    title: 'Fate Result Card',
    subtitle: 'FATE SCARRED — The Price of Defiance',
    kind: 'fate-result',
    description: 'High-stakes collectible Destiny Outcome card with irreversible narrative consequences.',
    explanation: {
      componentName: 'FateResultCard (inside SystemBlock)',
      sourceFile: 'src/components/reader-chamber/development/FateResultCard.tsx',
      currentTrigger: 'Structured block.system fate_result event',
      entityOrEventType: 'fate_result',
      codexDestination: 'ReaderCodex > Fate & Destiny Sovereign',
      capabilities: { hasImage: false, hasManifestAction: false, hasAudio: false, hasCodexLink: true, hasQuoteOrProse: true },
      architecturalNotes: 'Fate remains routed only through the existing SystemBlock presentation.',
    },
    systemContent: '[ FATE SCARRED: Rin shattered the Magistrate\'s Blood Oath at great personal cost ]',
    systemEvent: {
      kind: 'fate_result',
      title: 'Destiny Divergence Manifested',
      fateResult: {
        outcome: 'FATE SCARRED',
        timelineScar: 'Left arm spiritual meridians permanently sealed against celestial Qi.',
        permanentCosts: [
          'Cannot channel direct lightning or thunderstorm arts without severe backlash.',
          'Disabled off-hand spellcasting',
          'Rain sight limited to right eye',
        ],
        newStoryState: 'First false oath exposed before the Rain Court',
        newActiveStats: ['Willpower +25', 'Left Arm Flow: 0%', 'Karmic Weight: Heavy'],
      },
    },
  },
  {
    id: 'preset-manifestation-image',
    title: 'Manifestation Image',
    subtitle: 'Chapter 1 Crux Visual Memory',
    kind: 'manifestation-image',
    referenceOnly: true,
    description: 'Legacy chapter-level artwork retained only for the locked production Reference pane.',
    explanation: {
      componentName: 'ManifestationImage',
      sourceFile: 'src/components/reader-chamber/reference/ManifestationImage.tsx',
      currentTrigger: 'Legacy Reference snapshot only',
      entityOrEventType: 'chapter_crux_image (not an active entity card)',
      codexDestination: 'Legacy Reference snapshot only',
      capabilities: { hasImage: true, hasManifestAction: false, hasAudio: false, hasCodexLink: false, hasQuoteOrProse: true },
      architecturalNotes: 'Chapter Visual Memories are removed from the active Reader and Development Workshop.',
    },
    manifestationImage: {
      url: '/card-workshop/test-images/sergeant_anya_petrova_portrait.png',
      caption: 'The Rain Court Stands in Silence as the Broken Oath Is Revealed',
      chapterNumber: 1,
      quote: '"Your oath has a seam, Magistrate."',
    },
  },
];

/** Active Workshop presets exclude legacy production-reference snapshots. */
export const ACTIVE_CARD_PRESETS = CARD_PRESETS.filter(preset => !preset.referenceOnly);
